 
application.name=erasio
#ev1Qu3@dm1n
#{bcrypt}$2a$10$T52dc9AB86NAOjJFtx09eeCxNICKYHS9em0z1Cm3SUDw4os5HMUx6
server.port=8080
server.error.include-message = always

##Database Properties
spring.datasource.platform=mysql
#spring.datasource.url=jdbc:mysql://dev-bed.crtnzd4gzgot.ap-south-1.rds.amazonaws.com:3306/medical
spring.datasource.url=jdbc:mysql://localhost:3306/erasio
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Preethu@777
spring.datasource.initialization-mode=always
 	
#JPA Settings
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
#while testing
spring.jpa.hibernate.ddl-auto=update
#for Production
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.defer-datasource-initialization=true

jwt.secret=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2MzcxNDQ3NzgsImV4cCI6NDgyNDM1NDM3OCwiYXVkIjoiZXZpcXVlLWRpZ2l0YWwiLCJzdWIiOiJldmlxdWUtZGlnaXRhbCIsIkVtYWlsIjoic3VwcG9ydEBjeW5lZmlhbi5jb20ifQ.Nd9aY6wPYlWjT3Zv57udKbkyfjh-ePrWaVwH6WtcuLc


## jwt.secret.key=cynefian
#app.code=energynow


## Mail  server properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=preethampreethu852@gmail.com
spring.mail.password=hpwu vyle zdho pyxi  
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000




#build properties
ci.build.version=%ciBuildVersion%
ci.build.branch=%ciBuildBranch%
ci.build.env=%ciBuildEnv%
ci.git.hash=%ciGitHash%
ci.build.timestamp=%ciBuildTimestamp%